
namespace GGolbik.SecurityTools.X509.Models;

/// <summary>
/// A certificate MUST NOT include more than one instance of a particular extension.
/// 
/// Conforming CAs MUST support
/// - key identifiers (Sections 4.2.1.1 and 4.2.1.2),
/// - basic constraints (Section 4.2.1.9),
/// - key usage (Section4.2.1.3), and 
/// - certificate policies (Section 4.2.1.4)
/// extensions.
/// 
/// If the CA issues certificates with an empty sequence for the subject
/// field, the CA MUST support the subject alternative name extension
/// (Section 4.2.1.6).
/// 
/// Support for the remaining extensions is OPTIONAL.
/// 
/// 4.2.1.1.  Authority Key Identifier:
/// The keyIdentifier field of the authorityKeyIdentifier extension MUST
/// be included in all certificates generated by conforming CAs to
/// facilitate certification path construction.
/// 
/// 4.2.1.2.  Subject Key Identifier:
/// To facilitate certification path construction, this extension MUST
/// appear in all conforming CA certificates
/// </summary>
public class ConfigExtensions
{
    /// <summary>
    /// Indicates a particular version of the <see cref="ConfigExtensions"/>.
    /// </summary>
    public SchemaVersion? SchemaVersion { get; set; } = "1.0";

    public ConfigKeyUsageExtension? KeyUsage { get; set; }

    public ConfigExtendedKeyUsageExtension? ExtendedKeyUsage { get; set; }

    public ConfigSubjectAlternativeName? SubjectAlternativeName { get; set; }

    public ConfigBasicConstraintsExtension? BasicConstraints { get; set; }

    public ConfigSubjectKeyIdentifierExtension? SubjectKeyIdentifier { get; set; }

    public ConfigAuthorityKeyIdentifierExtension? AuthorityKeyIdentifier { get; set; }

    public IList<ConfigExtensionDefault>? Extensions { get; set; }
}

