
namespace GGolbik.SecurityTools.X509.Infos;

/// <summary>
/// 4.2.1.1.  Authority Key Identifier:
/// The keyIdentifier field of the authorityKeyIdentifier extension MUST
/// be included in all certificates generated by conforming CAs to
/// facilitate certification path construction.
/// </summary>
public class AuthorityKeyIdentifierExtensionInfo : X509ExtensionInfo
{
    /// <summary>
    /// KeyIdentifier or IssuerAndSerial
    /// </summary>
    public byte[]? AuthorityKeyIdentifier { get; set; }

}